x86-64-level: make more use of sed when called

diff --git a/x86-64-level b/x86-64-level
--- a/x86-64-level
+++ b/x86-64-level
@@ -90,21 +90,19 @@ read_input() {
 }
 
 get_cpu_name() {
-    name=$(echo "${data}" | grep -E "^model name[[:space:]]*:" | head -n 1)
-    name="${name#model name*:}"
-    echo "${name## }"
+    printf '%s\n' "${data}" |
+        sed -ne '/^model name[[:space:]]*:/{ s/^model name[[:space:]]*:[[:space:]]*//p;q }'
 }
 
 
 get_cpu_flags() {
-    flags=$(echo "${data}" | grep "^flags[[:space:]]*:" | head -n 1)
-    flags="${flags#*:}"
-    flags="${flags## }"
+    flags=$(printf '%s\n' "${data}" |
+        sed -ne '/^flags[[:space:]]*:/{ s/^flags[[:space:]]*:[[:space:]]*//p;q }')
     if [ "${flags}" != "${flags#*[!a-z0-9_ ]*}" ]; then
-        echo >&2 "ERROR: Cannot reliably infer the CPU x86-64 level, because the format of the CPU flags comprise of other symbols than only lower-case letters, digits, and underscores: '${flags}'"
+        >&2 printf '%s\n' "ERROR: Cannot reliably infer the CPU x86-64 level, because the format of the CPU flags comprise of other symbols than only lower-case letters, digits, and underscores: '${flags}'"
         exit 1
     fi
-    echo "${flags}"
+    printf '%s\n' "${flags}"
 }
 
 
