x86-64-level: simplify logic, call get_*() once

diff --git a/x86-64-level b/x86-64-level
--- a/x86-64-level
+++ b/x86-64-level
@@ -102,13 +102,12 @@ get_cpu_flags() {
         (*[!a-z0-9_\ ]*)
             >&2 printf '%s\n' "ERROR: Cannot reliably infer the CPU x86-64 level: only a-z, 0-9, and '_' expected in CPU flags; got: '${flags}'"
             exit 1
+            ;;
+        ('')
+            >&2 printf '%s\n' "ERROR: No CPU 'flags' entry in the input data"
+            exit 1
+            ;;
     esac
-    printf '%s\n' "${flags}"
-}
-
-
-validate_cpu_flags() {
-    get_cpu_flags > /dev/null
 }
 
 
@@ -122,7 +121,6 @@ has_cpu_flags() {
             (*)
                 if ${verbose}; then
                     msg="Identified x86-64-v${level}, because x86-64-v$((level + 1)) requires '${flag}', which is not supported by this CPU"
-                    cpu_name=$(get_cpu_name)
                     msg="${msg}${cpu_name:+ [${cpu_name}]}"
                     >&2 printf '%s\n' "${msg}"
                 fi
@@ -154,17 +152,6 @@ determine_cpu_version() {
     ## x86-64-v4
     has_cpu_flags avx512f avx512bw avx512cd avx512dq avx512vl || return 0
     level=4
-}
-
-
-report_cpu_version() {
-    flags=$(get_cpu_flags)
-    if [ -z "${flags}" ]; then
-        >&2 printf '%s\n' "ERROR: No CPU 'flags' entry in the input data"
-        exit 1
-    fi
-    determine_cpu_version
-    printf '%s\n' "${level}"
 }
 
 
@@ -221,16 +208,15 @@ while [ $# -gt 0 ]; do
 done
 
 read_input
+get_cpu_flags
+determine_cpu_version
+cpu_name=$(get_cpu_name)
+
 if [ -n "${assert}" ]; then
-    validate_cpu_flags
-    version=$(report_cpu_version)
-    if [ "${version}" -lt "${assert}" ]; then
-        cpu_info=$(get_cpu_name)
-        [ -n "${cpu_info}" ] && cpu_info=" [${cpu_info}]"
-        >&2 printf '%s\n' "The CPU${cpu_info} on this host ('$(hostname)') supports x86-64-v${version}, which is less than the required x86-64-v${assert}"
+    if [ "${level}" -lt "${assert}" ]; then
+        >&2 printf '%s\n' "The CPU${cpu_name:+ [${cpu_name}]} on this host ('$(hostname)') supports x86-64-v${level}, which is less than the required x86-64-v${assert}"
         exit 1
     fi
 else
-    validate_cpu_flags
-    report_cpu_version
+    printf '%s\n' "${level}"
 fi
